### ISSUE TITLE
[:bug:] Outdated GitHub-related links

### ISSUE THREAD

**Issue by joaopalmeiro** [jawah/kiss-headers#54]
Hi! 👋 

**Describe the bug**

If I'm correct, some links to the project repository as well as documentation are out of date, given that `ousret` should be updated to `jawah`. 

I noticed this in the `README.md`, `pyproject.toml`, and `mkdocs.yml` files, but I believe there are others that may need to be updated. The repository website URL on the right side of the project's GitHub page is also out of date. Please let me know if I can help in any way.

**To Reproduce**

- Go to https://ousret.github.io/kiss-headers/
- Go to https://jawah.github.io/kiss-headers/

Thanks! 😄

**Comment by Ousret** [comment]
Yes, you are right. I've updated the main documentation url.
If you are up to, you may issue a PR to update the remaining urls.

regards,
